# localstack-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: secretsmanager
            - name: DEFAULT_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              value: fake
            - name: AWS_SECRET_ACCESS_KEY
              value: fake
