# secretstore-localstack.yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: localstack-secrets
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: access-key
          secretAccessKeySecretRef:
            name: aws-creds
            key: secret-access-key
